name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.4.1
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 
  dio: 
  flutter_local_notifications: 
  rxdart: 
  open_filex:
  path_provider: 
  permission_handler: 
  package_info_plus: 
  sensors_plus: 
  share_plus: 
  chopper: 
  collection: 
  url_launcher: 

dev_dependencies:
  very_good_analysis: 

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.alice
        pluginClass: AlicePlugin
      ios:
        pluginClass: AlicePlugin
      macos:
        pluginClass: AlicePlugin
